---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fileshare
  namespace: {{.Values.namespace}}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2000Mi

