---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: lab
spec:
  type: ClusterIP
  selector:
    app: postgres-app
  ports:
    - name: '5432'
      port: 5432
      targetPort: 5432